# Ruby CircleCI 2.0 configuration file.
# Check https://circleci.com/docs/2.0/language-ruby/ for more details.
version: 2.1
jobs:
  ruby_v2_4:
    machine:
      image: "circleci/ruby:2.4.9"
    working_directory: "~/repo"
    steps:
      - "checkout"
      - restore_cache:
          key: "ruby-v2.4-gems-{{ checksum \"Gemfile.lock\" }}"
      - run:
          name: "Install gems"
          command: "bundle install --jobs=4 --path=vendor/bundle"
      - save_cache:
          key: "ruby-v2.4-gems-{{ checksum \"Gemfile.lock\" }}"
          paths:
            - "vendor/bundle"
      - run:
          name: "Execute tests"
          command: "bundle exec rspec"
  ruby_v2_5:
    machine:
      image: "circleci/ruby:2.5.7"
    working_directory: "~/repo"
    steps:
      - "checkout"
      - restore_cache:
          key: "ruby-v2.5-gems-{{ checksum \"Gemfile.lock\" }}"
      - run:
          name: "Install gems"
          command: "bundle install --jobs=4 --path=vendor/bundle"
      - save_cache:
          key: "ruby-v2.5-gems-{{ checksum \"Gemfile.lock\" }}"
          paths:
            - "vendor/bundle"
      - run:
          name: "Execute tests"
          command: "bundle exec rspec"
  ruby_v2_6:
    machine:
      image: "circleci/ruby:2.6.5"
    working_directory: "~/repo"
    steps:
      - "checkout"
      - restore_cache:
          key: "ruby-v2.6-gems-{{ checksum \"Gemfile.lock\" }}"
      - run:
          name: "Install gems"
          command: "bundle install --jobs=4 --path=vendor/bundle"
      - save_cache:
          key: "ruby-v2.6-gems-{{ checksum \"Gemfile.lock\" }}"
          paths:
            - "vendor/bundle"
      - run:
          name: "Execute tests"
          command: "bundle exec rspec"
  ruby_v2_7:
    machine:
      image: "circleci/ruby:2.7.0"
    working_directory: "~/repo"
    steps:
      - "checkout"
      - restore_cache:
          key: "ruby-v2.7-gems-{{ checksum \"Gemfile.lock\" }}"
      - run:
          name: "Install gems"
          command: "bundle install --jobs=4 --path=vendor/bundle"
      - save_cache:
          key: "ruby-v2.7-gems-{{ checksum \"Gemfile.lock\" }}"
          paths:
            - "vendor/bundle"
      - run:
          name: "Execute tests"
          command: "bundle exec rspec"
workflows:
  version: 2
  build:
    jobs:
      - "ruby_v2_4"
      - "ruby_v2_5"
      - "ruby_v2_6"
      - "ruby_v2_7"
