name: "Build and test"
on:
  push:
    branches: ["master"]
  pull_request: {}
jobs:

  parameters:
    name: "Set parameters"
    runs-on: "ubuntu-latest"
    outputs:
      GITHUB_SHA: "${{ steps.GITHUB_SHA.outputs.GITHUB_SHA }}"
    steps:
      - id: "GITHUB_SHA"
        run: "echo \"::set-output name=GITHUB_SHA::$GITHUB_SHA\""

  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    needs: "parameters"
    strategy:
      matrix:
        ruby: ["2.4", "2.5", "2.6"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Ruby"
        uses: "actions/setup-ruby@v1"
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: "Cache dependencies"
        id: "gem-dependencies"
        uses: "actions/cache@v2"
        with:
          path: "./vendor/bundle"
          key: "gem-${{ needs.parameters.outputs.GITHUB_SHA }}-${{ matrix.ruby }}"
      - name: "Install dependencies if needed"
        if: "steps.gem-dependencies.outputs.cache-hit != 'true'"
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4

  test:
    name: "Test"
    needs: ["parameters", "build"]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: ["2.4", "2.5", "2.6"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Ruby"
        uses: "actions/setup-ruby@v1"
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: "Restore cached dependencies"
        id: "gem-dependencies"
        uses: "actions/cache@v2"
        with:
          path: "./vendor/bundle"
          key: "gem-${{ needs.parameters.outputs.GITHUB_SHA }}-${{ matrix.ruby }}"
      - name: "Execute tests without coverage rate"
        if: "matrix.ruby != '2.6'"
        run: "bundle exec rspec"
      - name: "Execute tests with coverage rate"
        if: "matrix.ruby == '2.6'"
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        run: "bundle exec rspec"

  lint:
    name: "Lint"
    needs: ["parameters", "build"]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: ["2.4", "2.5", "2.6"]
    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Ruby"
        uses: "actions/setup-ruby@v1"
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: "Restore cached dependencies"
        id: "gem-dependencies"
        uses: "actions/cache@v2"
        with:
          path: "./vendor/bundle"
          key: "gem-${{ needs.parameters.outputs.GITHUB_SHA }}-${{ matrix.ruby }}"
      - name: "Execute linters"
        run: "bundle exec rubocop -P"
